const global = {
    BIZ9_MOBILE_VERSION:'8.4.3',
    APP_VERSION:'1.0.0',
    PROJECT_ID:'19',
    APP_VENDOR:'BiZ9 Framework Mobile',
    APP_TITLE:'Test 19',
    APP_TITLE_ID:'mobile-19',
    TEST_MODE:'true',
    CLOUD_URL:'http://localhost:1901',
    DEVICE_TYPE_IOS:'iOS',
    DEVICE_TYPE_ANDROID:'Android',
    DT_BLANK:'blank_biz',
    DT_BLOG_POST:'blog_post_biz',
    DT_OPTION:'option_biz',
    DT_CATEGORY:'category_biz',
    DT_EVENT:'event_biz',
    DT_GALLERY:'gallery_biz',
    DT_ITEM:'item_biz',
    DT_MEMBER:'member_biz',
    DT_PHOTO:'photo_biz',
    DT_PRODUCT:'product_biz',
    DT_REVIEW:'review_biz',
    DT_SERVICE:'service_biz',
    DT_SPORT:'sport_biz',
    DT_SPORT_STAT:'sport_stat_biz',
    DT_GAME:'game_biz',
    DT_TEAM:'team_biz',
    DT_PLAYER:'player_biz',
    DT_COACH:'coach_biz',
    DT_PAGE:'page',
    PAYMENT_TYPE_PAY_NOW:'pay_now',
    PAYMENT_TYPE_CASHAPP:'cashapp',
    PAYMENT_TYPE_ON_DELIVERY:'pay_on_delivery',
    NOTIFICATION_SUBSCRIBE_ALL:'mobile_all',
    NOTIFICATION_SUBSCRIBE_ADMIN:'mobile_admin',
    NOTIFICATION_SUBSCRIBE_GUEST:'mobile_guest',
    STAT_VIEW_ID:'1',
    STAT_LIKE_ID:'2',
    STAT_POST_ID:'3',
    COOKIE_CUSTOMER:'cookie_customer'
}
export default global;


